name: build

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rails: ["7.1", "7.0", "6.1", "6.0"]
        ruby: ["3.3.1", "3.2.4", "3.1.5", "3.0.7", "2.7.8"]
        include:
          - rails: "5.2"
            ruby: "2.7.8"
          - rails: "5.1"
            ruby: "2.6.10"
          - rails: "5.0"
            ruby: "2.6.10"

    env:
      RUBY_VERSION: ${{ matrix.ruby }}
      RAILS_VERSION: ${{ matrix.rails }}

    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec
