name: "RuboCop Challenge"

on:
  schedule:
    - cron: '30 23 * * 1,3,5' # Monday, Wednesday, Friday at 23:30 UTC

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: gemfiles/Gemfile.rails50
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.6
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: bundle install --jobs 4 --retry 3
      - name: Set git configuration
        run: git config remote.origin.url "git@github.com:Apipie/apipie-rails.git"
      - name: Create RuboCop challenge pull request
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bundle exec rubocop_challenger go --exclude-limit=180 --base-branch=master --email=rubocop@payrollhero.com --name="Rubocop Challenger" --mode=random
